# 基础镜像
FROM nginx
# author
MAINTAINER teaching

# 挂载目录
VOLUME /home/teaching/projects/teaching-ui
# 创建目录
RUN mkdir -p /home/teaching/projects/teaching-ui
# 指定路径
WORKDIR /home/teaching/projects/teaching-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/teaching/projects/teaching-ui
