# 基础镜像
FROM redis
# author
MAINTAINER teaching

# 挂载目录
VOLUME /home/teaching/redis
# 创建目录
RUN mkdir -p /home/teaching/redis
# 指定路径
WORKDIR /home/teaching/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/teaching/redis/redis.conf
