-- Competition on-site credential and verification tables.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only creates new tables and does not modify existing data.

SET NAMES utf8mb4;

-- 赛场安排主表：维护报道、赛场、候场、资料领取等真实现场安排。
CREATE TABLE IF NOT EXISTS `competition_scene_schedule` (
  `schedule_id` bigint NOT NULL AUTO_INCREMENT COMMENT '赛场安排ID',
  `schedule_name` varchar(255) NOT NULL COMMENT '安排名称',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `competition_name` varchar(255) DEFAULT NULL COMMENT '赛事名称快照',
  `competition_stage_id` varchar(64) DEFAULT NULL COMMENT '赛事阶段ID',
  `competition_stage_name` varchar(255) DEFAULT NULL COMMENT '赛事阶段名称快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR参赛证/TEACHER教师证/EXPERT专家证',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM团队/PERSON个人',
  `report_start_time` datetime DEFAULT NULL COMMENT '报道开始时间',
  `report_end_time` datetime DEFAULT NULL COMMENT '报道结束时间',
  `report_location` varchar(500) DEFAULT NULL COMMENT '报道地点',
  `contest_start_time` datetime DEFAULT NULL COMMENT '赛场开始时间',
  `contest_end_time` datetime DEFAULT NULL COMMENT '赛场结束时间',
  `contest_location` varchar(500) DEFAULT NULL COMMENT '赛场地点',
  `contest_room` varchar(255) DEFAULT NULL COMMENT '赛场/考场',
  `waiting_start_time` datetime DEFAULT NULL COMMENT '候场开始时间',
  `waiting_end_time` datetime DEFAULT NULL COMMENT '候场结束时间',
  `waiting_location` varchar(500) DEFAULT NULL COMMENT '候场地点',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `material_location` varchar(500) DEFAULT NULL COMMENT '资料领取地点',
  `notice` text COMMENT '注意事项',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态: 0启用/1停用',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`schedule_id`),
  KEY `idx_scene_schedule_series` (`competition_series_id`),
  KEY `idx_scene_schedule_track_group` (`competition_track_id`, `second_level_code`),
  KEY `idx_scene_schedule_type_dimension` (`credential_type`, `config_dimension`),
  KEY `idx_scene_schedule_status` (`status`, `del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场安排表';

-- 赛场安排对象表：记录某个安排匹配到的团队、个人或专家。
CREATE TABLE IF NOT EXISTS `competition_scene_schedule_target` (
  `target_id` bigint NOT NULL AUTO_INCREMENT COMMENT '安排对象ID',
  `schedule_id` bigint NOT NULL COMMENT '赛场安排ID',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR/TEACHER/EXPERT',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM/PERSON',
  `target_key` varchar(128) NOT NULL COMMENT '对象唯一键: TEAM:{teamCode}/PERSON:{memberId}/EXPERT:{manualKey}',
  `target_source` varchar(32) NOT NULL DEFAULT 'APPLY' COMMENT '对象来源: APPLY报名/IMPORT导入/MANUAL手工',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `id_card_type` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `id_card_hash` varchar(128) DEFAULT NULL COMMENT '证件号Hash',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位',
  `school` varchar(64) DEFAULT NULL COMMENT '学校编码',
  `school_name` varchar(255) DEFAULT NULL COMMENT '学校名称',
  `org_id` bigint DEFAULT NULL COMMENT '机构ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '机构名称',
  `competition_role_name` varchar(64) DEFAULT NULL COMMENT '参赛角色',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `leader_teacher_id` bigint DEFAULT NULL COMMENT '带队老师ID',
  `leader_teacher` varchar(100) DEFAULT NULL COMMENT '带队老师',
  `guide_teacher` varchar(500) DEFAULT NULL COMMENT '指导教师',
  `seat_no` varchar(64) DEFAULT NULL COMMENT '座位号/工位号',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `target_snapshot_json` longtext COMMENT '对象报名快照JSON',
  `match_status` varchar(32) NOT NULL DEFAULT 'MATCHED' COMMENT '匹配状态: MATCHED已匹配/CONFLICT冲突/INVALID无效',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态: 0有效/1停用',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`target_id`),
  UNIQUE KEY `uk_scene_target_key` (`schedule_id`, `target_key`),
  KEY `idx_scene_target_schedule` (`schedule_id`, `status`, `del_flag`),
  KEY `idx_scene_target_series` (`competition_series_id`),
  KEY `idx_scene_target_team` (`team_code`),
  KEY `idx_scene_target_member` (`member_id`),
  KEY `idx_scene_target_user` (`user_id`),
  KEY `idx_scene_target_track_group` (`competition_track_id`, `second_level_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场安排对象表';

-- 现场证件实例表：每个团队、个人或专家生成一张可扫码核验的证件。
CREATE TABLE IF NOT EXISTS `competition_scene_credential` (
  `credential_id` bigint NOT NULL AUTO_INCREMENT COMMENT '现场证件ID',
  `schedule_id` bigint NOT NULL COMMENT '赛场安排ID',
  `target_id` bigint DEFAULT NULL COMMENT '安排对象ID',
  `credential_no` varchar(64) NOT NULL COMMENT '证件编号',
  `credential_token` varchar(128) NOT NULL COMMENT '二维码令牌',
  `qr_content` varchar(1000) DEFAULT NULL COMMENT '二维码内容',
  `qr_code_url` varchar(1000) DEFAULT NULL COMMENT '二维码图片URL',
  `credential_file_url` varchar(1000) DEFAULT NULL COMMENT '参赛证文件URL',
  `credential_image_url` varchar(1000) DEFAULT NULL COMMENT '参赛证图片URL',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR参赛证/TEACHER教师证/EXPERT专家证',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM/PERSON',
  `subject_type` varchar(32) NOT NULL COMMENT '证件主体: TEAM团队/PERSON个人/EXPERT专家',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `competition_name` varchar(255) DEFAULT NULL COMMENT '赛事名称快照',
  `competition_stage_id` varchar(64) DEFAULT NULL COMMENT '赛事阶段ID',
  `competition_stage_name` varchar(255) DEFAULT NULL COMMENT '赛事阶段名称快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `id_card_type` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `id_card_hash` varchar(128) DEFAULT NULL COMMENT '证件号Hash',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位',
  `school` varchar(64) DEFAULT NULL COMMENT '学校编码',
  `school_name` varchar(255) DEFAULT NULL COMMENT '学校名称',
  `org_id` bigint DEFAULT NULL COMMENT '机构ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '机构名称',
  `competition_role_name` varchar(64) DEFAULT NULL COMMENT '参赛角色',
  `leader_teacher_id` bigint DEFAULT NULL COMMENT '带队老师ID',
  `leader_teacher` varchar(100) DEFAULT NULL COMMENT '带队老师',
  `guide_teacher` varchar(500) DEFAULT NULL COMMENT '指导教师',
  `report_start_time` datetime DEFAULT NULL COMMENT '报道开始时间快照',
  `report_end_time` datetime DEFAULT NULL COMMENT '报道结束时间快照',
  `report_location` varchar(500) DEFAULT NULL COMMENT '报道地点快照',
  `contest_start_time` datetime DEFAULT NULL COMMENT '赛场开始时间快照',
  `contest_end_time` datetime DEFAULT NULL COMMENT '赛场结束时间快照',
  `contest_location` varchar(500) DEFAULT NULL COMMENT '赛场地点快照',
  `contest_room` varchar(255) DEFAULT NULL COMMENT '赛场/考场快照',
  `seat_no` varchar(64) DEFAULT NULL COMMENT '座位号/工位号',
  `waiting_start_time` datetime DEFAULT NULL COMMENT '候场开始时间快照',
  `waiting_end_time` datetime DEFAULT NULL COMMENT '候场结束时间快照',
  `waiting_location` varchar(500) DEFAULT NULL COMMENT '候场地点快照',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `material_location` varchar(500) DEFAULT NULL COMMENT '资料领取地点快照',
  `notice` text COMMENT '注意事项快照',
  `credential_snapshot_json` longtext COMMENT '证件生成快照JSON',
  `valid_from` datetime DEFAULT NULL COMMENT '有效开始时间',
  `valid_to` datetime DEFAULT NULL COMMENT '有效结束时间',
  `credential_status` varchar(32) NOT NULL DEFAULT 'EFFECTIVE' COMMENT '证件状态: EFFECTIVE有效/REVOKED作废/EXPIRED过期',
  `verify_count` int NOT NULL DEFAULT 0 COMMENT '核验次数',
  `last_verify_time` datetime DEFAULT NULL COMMENT '最后核验时间',
  `report_status` char(1) NOT NULL DEFAULT '0' COMMENT '报道状态: 0未报到/1已报到',
  `report_time` datetime DEFAULT NULL COMMENT '报道时间',
  `report_operator_id` bigint DEFAULT NULL COMMENT '报道操作人ID',
  `report_operator_name` varchar(100) DEFAULT NULL COMMENT '报道操作人',
  `material_status` char(1) NOT NULL DEFAULT '0' COMMENT '资料领取状态: 0未领取/1已领取',
  `material_time` datetime DEFAULT NULL COMMENT '资料领取时间',
  `material_receiver_name` varchar(100) DEFAULT NULL COMMENT '资料领取人',
  `material_receiver_phone` varchar(32) DEFAULT NULL COMMENT '资料领取人手机号',
  `material_receiver_id_suffix` varchar(16) DEFAULT NULL COMMENT '资料领取人证件后六位',
  `material_operator_id` bigint DEFAULT NULL COMMENT '资料领取操作人ID',
  `material_operator_name` varchar(100) DEFAULT NULL COMMENT '资料领取操作人',
  `waiting_status` char(1) NOT NULL DEFAULT '0' COMMENT '候场状态: 0未候场/1已候场',
  `waiting_time` datetime DEFAULT NULL COMMENT '候场确认时间',
  `waiting_operator_id` bigint DEFAULT NULL COMMENT '候场操作人ID',
  `waiting_operator_name` varchar(100) DEFAULT NULL COMMENT '候场操作人',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`credential_id`),
  UNIQUE KEY `uk_scene_credential_no` (`credential_no`),
  UNIQUE KEY `uk_scene_credential_token` (`credential_token`),
  KEY `idx_scene_credential_schedule` (`schedule_id`),
  KEY `idx_scene_credential_target` (`target_id`),
  KEY `idx_scene_credential_series` (`competition_series_id`),
  KEY `idx_scene_credential_team` (`team_code`),
  KEY `idx_scene_credential_member` (`member_id`),
  KEY `idx_scene_credential_user` (`user_id`),
  KEY `idx_scene_credential_track_group` (`competition_track_id`, `second_level_code`),
  KEY `idx_scene_credential_status` (`credential_status`, `del_flag`),
  KEY `idx_scene_credential_report` (`report_status`, `report_time`),
  KEY `idx_scene_credential_material` (`material_status`, `material_time`),
  KEY `idx_scene_credential_waiting` (`waiting_status`, `waiting_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场证件实例表';

-- 现场操作流水表：记录扫码核验、报到签到、资料领取、候场确认及失败/重复操作。
CREATE TABLE IF NOT EXISTS `competition_scene_operation_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '现场操作日志ID',
  `credential_id` bigint DEFAULT NULL COMMENT '现场证件ID',
  `schedule_id` bigint DEFAULT NULL COMMENT '赛场安排ID',
  `target_id` bigint DEFAULT NULL COMMENT '安排对象ID',
  `competition_series_id` bigint DEFAULT NULL COMMENT '赛事系列ID',
  `credential_no` varchar(64) DEFAULT NULL COMMENT '证件编号',
  `credential_token` varchar(128) DEFAULT NULL COMMENT '二维码令牌',
  `operation_type` varchar(32) NOT NULL COMMENT '操作类型: VERIFY核验/REPORT_SIGN报道/MATERIAL_RECEIVE资料领取/WAITING_CHECK_IN候场',
  `operation_stage` varchar(32) NOT NULL DEFAULT 'CONFIRM' COMMENT '操作阶段: SCAN扫码/CONFIRM确认',
  `operation_result` varchar(32) NOT NULL COMMENT '操作结果: PASS通过/FAIL失败/DUPLICATE重复/EXCEPTION异常',
  `result_message` varchar(500) DEFAULT NULL COMMENT '结果说明',
  `apply_check_result` varchar(32) DEFAULT NULL COMMENT '报名一致性校验结果',
  `schedule_check_result` varchar(32) DEFAULT NULL COMMENT '赛场安排校验结果',
  `identity_check_result` varchar(32) DEFAULT NULL COMMENT '身份校验结果',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号快照',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称快照',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID快照',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID快照',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名快照',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `receiver_name` varchar(100) DEFAULT NULL COMMENT '资料领取人',
  `receiver_phone` varchar(32) DEFAULT NULL COMMENT '资料领取人手机号',
  `receiver_id_suffix` varchar(16) DEFAULT NULL COMMENT '资料领取人证件后六位',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人姓名',
  `operator_phone` varchar(32) DEFAULT NULL COMMENT '操作人手机号',
  `operator_open_id` varchar(128) DEFAULT NULL COMMENT '操作人微信OpenID',
  `scan_ip` varchar(128) DEFAULT NULL COMMENT '扫码IP',
  `device_info` varchar(500) DEFAULT NULL COMMENT '设备信息',
  `operation_time` datetime NOT NULL COMMENT '操作时间',
  `request_payload` longtext COMMENT '请求参数JSON',
  `response_payload` longtext COMMENT '响应结果JSON',
  `apply_snapshot_json` longtext COMMENT '当前报名快照JSON',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`log_id`),
  KEY `idx_scene_log_credential` (`credential_id`),
  KEY `idx_scene_log_schedule` (`schedule_id`),
  KEY `idx_scene_log_series` (`competition_series_id`),
  KEY `idx_scene_log_operation` (`operation_type`, `operation_stage`, `operation_result`),
  KEY `idx_scene_log_time` (`operation_time`),
  KEY `idx_scene_log_team` (`team_code`),
  KEY `idx_scene_log_member` (`member_id`),
  KEY `idx_scene_log_user` (`user_id`),
  KEY `idx_scene_log_operator` (`operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场扫码操作流水表';

