-- 通用评审模块第一包数据库结构。
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `review_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_name` varchar(200) NOT NULL COMMENT '评审活动名称',
  `activity_code` varchar(100) NOT NULL COMMENT '评审活动编码',
  `activity_type` varchar(50) DEFAULT NULL COMMENT '活动类型',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源业务模块',
  `source_biz_type` varchar(100) DEFAULT NULL COMMENT '来源业务类型',
  `object_type` varchar(50) DEFAULT NULL COMMENT '评审对象类型',
  `submission_mode` varchar(50) DEFAULT NULL COMMENT '填报模式',
  `submit_start_time` datetime DEFAULT NULL COMMENT '填报开始时间',
  `submit_deadline` datetime DEFAULT NULL COMMENT '填报截止时间',
  `review_start_time` datetime DEFAULT NULL COMMENT '评审开始时间',
  `review_end_time` datetime DEFAULT NULL COMMENT '评审结束时间',
  `anonymous_mode` varchar(50) DEFAULT NULL COMMENT '匿名模式',
  `result_publish_mode` varchar(50) DEFAULT NULL COMMENT '结果发布模式',
  `status` varchar(50) DEFAULT NULL COMMENT '活动状态',
  `description` text COMMENT '活动说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_activity_code` (`activity_code`),
  KEY `idx_review_activity_status` (`status`),
  KEY `idx_review_activity_source` (`source_module`, `source_biz_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审活动表';

CREATE TABLE IF NOT EXISTS `review_round` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '所属评审活动',
  `round_name` varchar(200) NOT NULL COMMENT '轮次名称',
  `round_no` int NOT NULL COMMENT '轮次序号',
  `round_type` varchar(50) DEFAULT NULL COMMENT '轮次类型',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `rule_id` bigint DEFAULT NULL COMMENT '评分规则ID',
  `status` varchar(50) DEFAULT NULL COMMENT '轮次状态',
  `description` text COMMENT '轮次说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_round_activity` (`activity_id`),
  KEY `idx_review_round_type` (`round_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审轮次表';

CREATE TABLE IF NOT EXISTS `review_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `rule_name` varchar(200) NOT NULL COMMENT '规则名称',
  `score_mode` varchar(50) DEFAULT NULL COMMENT '评分模式',
  `total_score` decimal(10,2) DEFAULT NULL COMMENT '总分',
  `anonymous_mode` varchar(50) DEFAULT NULL COMMENT '匿名模式',
  `description` text COMMENT '规则说明',
  `enabled` char(1) DEFAULT NULL COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_rule_activity_round` (`activity_id`, `round_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审规则表';

CREATE TABLE IF NOT EXISTS `review_criteria` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `rule_id` bigint DEFAULT NULL COMMENT '规则ID',
  `parent_id` bigint DEFAULT NULL COMMENT '父指标ID',
  `criteria_name` varchar(200) NOT NULL COMMENT '指标名称',
  `criteria_desc` text COMMENT '指标说明',
  `score_type` varchar(50) DEFAULT NULL COMMENT '评分项类型',
  `min_score` decimal(10,2) DEFAULT NULL COMMENT '最小分',
  `max_score` decimal(10,2) DEFAULT NULL COMMENT '最大分',
  `weight` decimal(10,4) DEFAULT NULL COMMENT '权重',
  `required` char(1) DEFAULT NULL COMMENT '是否必填',
  `options_json` text COMMENT '选项JSON',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `enabled` char(1) DEFAULT NULL COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_criteria_rule` (`rule_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评分指标表';

CREATE TABLE IF NOT EXISTS `review_object` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `object_code` varchar(100) NOT NULL COMMENT '评审对象编号',
  `object_name` varchar(300) NOT NULL COMMENT '评审对象名称',
  `object_type` varchar(50) DEFAULT NULL COMMENT '评审对象类型',
  `summary` text COMMENT '对象摘要',
  `subject_code_1` varchar(100) DEFAULT NULL COMMENT '学科代码1',
  `subject_code_2` varchar(100) DEFAULT NULL COMMENT '学科代码2',
  `subject_code_3` varchar(100) DEFAULT NULL COMMENT '学科代码3',
  `category_codes` text COMMENT '分类字段',
  `keywords` text COMMENT '关键词',
  `org_name` varchar(200) DEFAULT NULL COMMENT '所属单位',
  `contact_name` varchar(100) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(100) DEFAULT NULL COMMENT '联系方式',
  `contact_email` varchar(200) DEFAULT NULL COMMENT '联系邮箱',
  `submit_status` varchar(50) DEFAULT NULL COMMENT '填报状态',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `submitted_by` bigint DEFAULT NULL COMMENT '提交人',
  `locked_time` datetime DEFAULT NULL COMMENT '锁定时间',
  `invalid_time` datetime DEFAULT NULL COMMENT '作废时间',
  `created_from` varchar(50) DEFAULT NULL COMMENT '创建来源',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源模块',
  `source_biz_type` varchar(100) DEFAULT NULL COMMENT '来源业务类型',
  `source_biz_id` varchar(100) DEFAULT NULL COMMENT '外部业务ID',
  `source_team_id` varchar(100) DEFAULT NULL COMMENT '来源团队ID',
  `source_registration_id` varchar(100) DEFAULT NULL COMMENT '来源报名ID',
  `extra_data` text COMMENT '扩展字段JSON',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_object_code` (`activity_id`, `object_code`),
  KEY `idx_review_object_source` (`source_module`, `source_biz_type`, `source_biz_id`),
  KEY `idx_review_object_status` (`activity_id`, `submit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审对象表';

CREATE TABLE IF NOT EXISTS `review_object_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `person_id` varchar(100) DEFAULT NULL COMMENT '人员ID',
  `member_name` varchar(100) DEFAULT NULL COMMENT '成员姓名',
  `member_role` varchar(50) DEFAULT NULL COMMENT '成员角色',
  `is_primary` char(1) DEFAULT NULL COMMENT '是否主要成员',
  `phone` varchar(100) DEFAULT NULL COMMENT '电话',
  `email` varchar(200) DEFAULT NULL COMMENT '邮箱',
  `org_name` varchar(200) DEFAULT NULL COMMENT '单位',
  `certificate_id` varchar(100) DEFAULT NULL COMMENT '证件ID',
  `certificate_code` varchar(100) DEFAULT NULL COMMENT '证件编码',
  `certificate_type` varchar(50) DEFAULT NULL COMMENT '证件类型',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源模块',
  `source_biz_id` varchar(100) DEFAULT NULL COMMENT '来源业务ID',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_object_member_object` (`object_id`),
  KEY `idx_review_object_member_user` (`user_id`),
  KEY `idx_review_object_member_cert` (`certificate_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审对象成员表';

CREATE TABLE IF NOT EXISTS `review_object_material` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `material_name` varchar(300) DEFAULT NULL COMMENT '材料名称',
  `material_type` varchar(50) DEFAULT NULL COMMENT '材料类型',
  `file_name` varchar(300) DEFAULT NULL COMMENT '文件名称',
  `file_url` varchar(1000) DEFAULT NULL COMMENT '文件地址',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `mime_type` varchar(200) DEFAULT NULL COMMENT 'MIME类型',
  `file_ext` varchar(50) DEFAULT NULL COMMENT '文件扩展名',
  `visible_to_reviewer` char(1) DEFAULT NULL COMMENT '专家可见',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `upload_by` bigint DEFAULT NULL COMMENT '上传人',
  `upload_time` datetime DEFAULT NULL COMMENT '上传时间',
  `status` varchar(50) DEFAULT NULL COMMENT '材料状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_object_material_object` (`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审材料表';

CREATE TABLE IF NOT EXISTS `review_submission_permission` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `org_id` bigint DEFAULT NULL COMMENT '组织ID',
  `permission_type` varchar(50) DEFAULT NULL COMMENT '权限类型',
  `status` varchar(50) DEFAULT NULL COMMENT '权限状态',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源模块',
  `source_biz_id` varchar(100) DEFAULT NULL COMMENT '来源业务ID',
  `granted_by` bigint DEFAULT NULL COMMENT '授权人',
  `granted_time` datetime DEFAULT NULL COMMENT '授权时间',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_permission_user` (`activity_id`, `user_id`),
  KEY `idx_review_permission_object` (`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='填报权限表';

CREATE TABLE IF NOT EXISTS `review_object_external_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源模块',
  `source_biz_type` varchar(100) DEFAULT NULL COMMENT '来源业务类型',
  `source_biz_id` varchar(100) DEFAULT NULL COMMENT '来源业务ID',
  `source_biz_code` varchar(100) DEFAULT NULL COMMENT '来源业务编码',
  `source_team_id` varchar(100) DEFAULT NULL COMMENT '来源团队ID',
  `source_registration_id` varchar(100) DEFAULT NULL COMMENT '来源报名ID',
  `relation_type` varchar(50) DEFAULT NULL COMMENT '关联类型',
  `extra_data` text COMMENT '扩展字段JSON',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_external_object` (`object_id`),
  KEY `idx_review_external_source` (`source_module`, `source_biz_type`, `source_biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='外部业务关联表';

CREATE TABLE IF NOT EXISTS `review_object_certificate_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `certificate_id` varchar(100) DEFAULT NULL COMMENT '证件ID',
  `certificate_code` varchar(100) DEFAULT NULL COMMENT '证件编码',
  `certificate_type` varchar(50) DEFAULT NULL COMMENT '证件类型',
  `person_id` varchar(100) DEFAULT NULL COMMENT '人员ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `member_id` bigint DEFAULT NULL COMMENT '成员ID',
  `member_name` varchar(100) DEFAULT NULL COMMENT '成员姓名',
  `member_role` varchar(50) DEFAULT NULL COMMENT '成员角色',
  `source_module` varchar(100) DEFAULT NULL COMMENT '来源模块',
  `source_biz_id` varchar(100) DEFAULT NULL COMMENT '来源业务ID',
  `source_team_id` varchar(100) DEFAULT NULL COMMENT '来源团队ID',
  `source_registration_id` varchar(100) DEFAULT NULL COMMENT '来源报名ID',
  `valid_status` varchar(50) DEFAULT NULL COMMENT '有效状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_cert_activity_code` (`activity_id`, `certificate_code`),
  KEY `idx_cert_object` (`object_id`),
  KEY `idx_cert_source` (`source_module`, `source_biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审对象参赛证映射表';

CREATE TABLE IF NOT EXISTS `reviewer_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `reviewer_name` varchar(100) NOT NULL COMMENT '评审人姓名',
  `org_name` varchar(200) DEFAULT NULL COMMENT '单位',
  `phone` varchar(100) DEFAULT NULL COMMENT '电话',
  `email` varchar(200) DEFAULT NULL COMMENT '邮箱',
  `subject_code_1` varchar(100) DEFAULT NULL COMMENT '学科代码1',
  `subject_code_2` varchar(100) DEFAULT NULL COMMENT '学科代码2',
  `subject_code_3` varchar(100) DEFAULT NULL COMMENT '学科代码3',
  `category_codes` text COMMENT '分类字段',
  `keywords` text COMMENT '关键词',
  `max_task_count` int DEFAULT NULL COMMENT '最大任务数',
  `status` varchar(50) DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_reviewer_profile_user` (`user_id`),
  KEY `idx_reviewer_profile_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审人画像表';

CREATE TABLE IF NOT EXISTS `review_activity_user_role` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `role_type` varchar(50) DEFAULT NULL COMMENT '角色类型',
  `reviewer_id` bigint DEFAULT NULL COMMENT '评审人ID',
  `panel_id` bigint DEFAULT NULL COMMENT '专家组ID',
  `enabled` char(1) DEFAULT NULL COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_role_activity_user` (`activity_id`, `user_id`),
  KEY `idx_review_role_reviewer` (`reviewer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='活动内用户角色表';

CREATE TABLE IF NOT EXISTS `review_panel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `panel_name` varchar(200) DEFAULT NULL COMMENT '专家组名称',
  `panel_code` varchar(100) DEFAULT NULL COMMENT '专家组编码',
  `leader_user_id` bigint DEFAULT NULL COMMENT '组长用户ID',
  `secretary_user_id` bigint DEFAULT NULL COMMENT '秘书用户ID',
  `status` varchar(50) DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_panel_activity_round` (`activity_id`, `round_id`),
  KEY `idx_review_panel_code` (`panel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='专家组表';

CREATE TABLE IF NOT EXISTS `review_panel_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `panel_id` bigint DEFAULT NULL COMMENT '专家组ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `reviewer_id` bigint DEFAULT NULL COMMENT '评审人ID',
  `member_role` varchar(50) DEFAULT NULL COMMENT '成员角色',
  `status` varchar(50) DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_panel_member_panel` (`panel_id`),
  KEY `idx_review_panel_member_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='专家组成员表';

CREATE TABLE IF NOT EXISTS `review_assignment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `reviewer_id` bigint DEFAULT NULL COMMENT '评审人ID',
  `reviewer_user_id` bigint DEFAULT NULL COMMENT '评审用户ID',
  `panel_id` bigint DEFAULT NULL COMMENT '专家组ID',
  `assignment_type` varchar(50) DEFAULT NULL COMMENT '分配类型',
  `status` varchar(50) DEFAULT NULL COMMENT '分配状态',
  `assigned_by` bigint DEFAULT NULL COMMENT '分配人',
  `assigned_time` datetime DEFAULT NULL COMMENT '分配时间',
  `submitted_time` datetime DEFAULT NULL COMMENT '提交时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_assignment_user` (`activity_id`, `round_id`, `object_id`, `reviewer_user_id`),
  KEY `idx_review_assignment_reviewer` (`reviewer_id`),
  KEY `idx_review_assignment_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审任务分配表';

CREATE TABLE IF NOT EXISTS `review_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `assignment_id` bigint DEFAULT NULL COMMENT '分配ID',
  `reviewer_id` bigint DEFAULT NULL COMMENT '评审人ID',
  `reviewer_user_id` bigint DEFAULT NULL COMMENT '评审用户ID',
  `record_status` varchar(50) DEFAULT NULL COMMENT '记录状态',
  `total_score` decimal(10,2) DEFAULT NULL COMMENT '总分',
  `grade` varchar(50) DEFAULT NULL COMMENT '等级',
  `recommendation` varchar(100) DEFAULT NULL COMMENT '推荐意见',
  `comment_text` text COMMENT '评语',
  `submitted_time` datetime DEFAULT NULL COMMENT '提交时间',
  `returned_time` datetime DEFAULT NULL COMMENT '退回时间',
  `locked_time` datetime DEFAULT NULL COMMENT '锁定时间',
  `invalid_time` datetime DEFAULT NULL COMMENT '作废时间',
  `invalid_reason` varchar(500) DEFAULT NULL COMMENT '作废原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_record_assignment` (`assignment_id`),
  KEY `idx_review_record_object` (`activity_id`, `round_id`, `object_id`),
  KEY `idx_review_record_reviewer` (`reviewer_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='专家评审记录表';

CREATE TABLE IF NOT EXISTS `review_score_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `record_id` bigint DEFAULT NULL COMMENT '评审记录ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `criteria_id` bigint DEFAULT NULL COMMENT '指标ID',
  `criteria_name` varchar(200) NOT NULL COMMENT '指标名称快照',
  `score_type` varchar(50) DEFAULT NULL COMMENT '评分项类型',
  `score_value` decimal(10,2) DEFAULT NULL COMMENT '得分',
  `option_value` varchar(200) DEFAULT NULL COMMENT '选项值',
  `text_value` text COMMENT '文本评价',
  `weight` decimal(10,4) DEFAULT NULL COMMENT '权重快照',
  `sort_order` int DEFAULT NULL COMMENT '排序',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_score_record` (`record_id`),
  KEY `idx_review_score_object` (`activity_id`, `round_id`, `object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评分明细表';

CREATE TABLE IF NOT EXISTS `review_session` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `session_name` varchar(200) NOT NULL COMMENT '场次名称',
  `session_code` varchar(100) NOT NULL COMMENT '场次编码',
  `location` varchar(200) DEFAULT NULL COMMENT '地点',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `secretary_user_id` bigint DEFAULT NULL COMMENT '秘书用户ID',
  `panel_id` bigint DEFAULT NULL COMMENT '专家组ID',
  `current_object_id` bigint DEFAULT NULL COMMENT '当前评审对象ID',
  `current_started_time` datetime DEFAULT NULL COMMENT '当前对象开始时间',
  `status` varchar(50) DEFAULT NULL COMMENT '场次状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_session_activity_round` (`activity_id`, `round_id`),
  KEY `idx_review_session_code` (`session_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='现场评审场次表';

CREATE TABLE IF NOT EXISTS `review_session_object` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `session_id` bigint DEFAULT NULL COMMENT '场次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `sequence_no` int DEFAULT NULL COMMENT '顺序号',
  `checkin_status` varchar(50) DEFAULT NULL COMMENT '签到状态',
  `review_status` varchar(50) DEFAULT NULL COMMENT '评审状态',
  `actual_start_time` datetime DEFAULT NULL COMMENT '实际开始时间',
  `actual_end_time` datetime DEFAULT NULL COMMENT '实际结束时间',
  `secretary_note` varchar(500) DEFAULT NULL COMMENT '秘书备注',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_session_object` (`session_id`, `object_id`),
  KEY `idx_session_sequence` (`session_id`, `sequence_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='现场评审对象顺序表';

CREATE TABLE IF NOT EXISTS `review_session_event_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `session_id` bigint DEFAULT NULL COMMENT '场次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `event_type` varchar(50) DEFAULT NULL COMMENT '事件类型',
  `event_content` text COMMENT '事件内容',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `event_time` datetime DEFAULT NULL COMMENT '事件时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_event_session` (`session_id`),
  KEY `idx_review_event_object` (`object_id`),
  KEY `idx_review_event_time` (`event_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='现场事件日志表';

CREATE TABLE IF NOT EXISTS `review_result` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `reviewer_count` int DEFAULT NULL COMMENT '应评专家数',
  `submitted_count` int DEFAULT NULL COMMENT '已提交数',
  `calculated_score` decimal(10,2) DEFAULT NULL COMMENT '系统计算分',
  `calculated_grade` varchar(50) DEFAULT NULL COMMENT '系统计算等级',
  `calculated_rank` int DEFAULT NULL COMMENT '系统计算排名',
  `evaluation_conclusion` varchar(500) DEFAULT NULL COMMENT '发布性评价结论',
  `conclusion_generated_by` bigint DEFAULT NULL COMMENT '结论填写人',
  `conclusion_generated_time` datetime DEFAULT NULL COMMENT '结论填写时间',
  `result_status` varchar(50) DEFAULT NULL COMMENT '结果状态',
  `generated_by` bigint DEFAULT NULL COMMENT '汇总人',
  `generated_time` datetime DEFAULT NULL COMMENT '汇总时间',
  `published_by` bigint DEFAULT NULL COMMENT '发布人',
  `published_time` datetime DEFAULT NULL COMMENT '发布时间',
  `revoked_by` bigint DEFAULT NULL COMMENT '撤销人',
  `revoked_time` datetime DEFAULT NULL COMMENT '撤销时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_result_object` (`activity_id`, `round_id`, `object_id`),
  KEY `idx_review_result_status` (`result_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评审结果表';

CREATE TABLE IF NOT EXISTS `review_result_publish_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `publish_scope` varchar(50) DEFAULT NULL COMMENT '发布范围',
  `publish_content` text COMMENT '发布内容',
  `published_by` bigint DEFAULT NULL COMMENT '发布人',
  `published_time` datetime DEFAULT NULL COMMENT '发布时间',
  `status` varchar(50) DEFAULT NULL COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_publish_activity` (`activity_id`, `round_id`),
  KEY `idx_review_publish_object` (`object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='结果发布日志表';

CREATE TABLE IF NOT EXISTS `review_audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '评审活动ID',
  `round_id` bigint DEFAULT NULL COMMENT '评审轮次ID',
  `object_id` bigint DEFAULT NULL COMMENT '评审对象ID',
  `biz_type` varchar(100) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(100) DEFAULT NULL COMMENT '业务ID',
  `action_type` varchar(100) DEFAULT NULL COMMENT '操作类型',
  `action_content` text COMMENT '操作内容',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人名称',
  `operate_time` datetime DEFAULT NULL COMMENT '操作时间',
  `ip_addr` varchar(100) DEFAULT NULL COMMENT 'IP地址',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_audit_biz` (`biz_type`, `biz_id`),
  KEY `idx_review_audit_object` (`activity_id`, `round_id`, `object_id`),
  KEY `idx_review_audit_time` (`operate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='审计日志表';
