-- Competition scene resource phase 1 tables.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only creates new tables and does not modify existing data.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `competition_scene_resource` (
  `resource_id` bigint NOT NULL AUTO_INCREMENT COMMENT '资源ID',
  `resource_code` varchar(64) NOT NULL COMMENT '资源编号',
  `resource_name` varchar(255) NOT NULL COMMENT '资源名称',
  `resource_type` varchar(32) NOT NULL COMMENT '资源类型: ROOM/LAB/DEVICE/WORKSTATION/SERVER/SOFTWARE/OTHER',
  `resource_status` varchar(32) NOT NULL COMMENT '资源状态: ENABLED启用/DISABLED停用/MAINTENANCE维护中',
  `brand_model` varchar(255) DEFAULT NULL COMMENT '品牌型号',
  `device_quantity` int NOT NULL COMMENT '设备数量',
  `workstation_count` int NOT NULL COMMENT '单台设备工位数',
  `default_slot_duration_minutes` int NOT NULL COMMENT '默认单场占用周期，单位分钟',
  `default_shared_occupancy` tinyint(1) NOT NULL DEFAULT 1 COMMENT '默认是否共享占用: 0否/1是',
  `need_ops_confirm` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要运维确认，仅提示字段: 0否/1是',
  `ops_contact_name` varchar(100) DEFAULT NULL COMMENT '运维联系人',
  `ops_contact_phone` varchar(32) DEFAULT NULL COMMENT '运维联系电话',
  `safety_notice` text COMMENT '安全须知',
  `attention_notes` text COMMENT '注意事项',
  `parameter_json` longtext COMMENT '主要参数列表JSON',
  `usage_instructions` text COMMENT '使用说明',
  `image_urls` longtext COMMENT '设备图片URL JSON数组',
  `admin_remark` varchar(500) DEFAULT NULL COMMENT '管理员备注',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`resource_id`),
  UNIQUE KEY `uk_scene_resource_code` (`resource_code`, `deleted`),
  KEY `idx_scene_resource_type` (`resource_type`),
  KEY `idx_scene_resource_status` (`resource_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源台账表';

CREATE TABLE IF NOT EXISTS `competition_scene_schedule_resource` (
  `schedule_resource_id` bigint NOT NULL AUTO_INCREMENT COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `deployment_location` varchar(500) DEFAULT NULL COMMENT '部署位置',
  `deployed_device_count` int NOT NULL COMMENT '部署设备数',
  `workstations_per_device` int NOT NULL COMMENT '每台设备工位数',
  `total_workstations` int NOT NULL COMMENT '总工位数',
  `slot_duration_minutes` int NOT NULL COMMENT '单场占用周期，单位分钟',
  `shared_occupancy` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否共享占用: 0否/1是',
  `need_ops_confirm` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要运维确认，仅提示字段: 0否/1是',
  `ops_contact_name` varchar(100) DEFAULT NULL COMMENT '运维联系人',
  `ops_contact_phone` varchar(32) DEFAULT NULL COMMENT '运维联系电话',
  `booking_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '预约发布状态: DRAFT/READY/OPEN/PAUSED/CLOSED',
  `booking_open_time` datetime DEFAULT NULL COMMENT '预约开放时间',
  `booking_close_time` datetime DEFAULT NULL COMMENT '预约关闭时间',
  `safety_notice_override` text COMMENT '安全须知覆盖',
  `attention_notes_override` text COMMENT '注意事项覆盖',
  `usage_instructions_override` text COMMENT '使用说明覆盖',
  `admin_remark` varchar(500) DEFAULT NULL COMMENT '管理员备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`schedule_resource_id`),
  KEY `idx_scene_schedule_resource_schedule` (`schedule_id`, `deleted`),
  KEY `idx_scene_schedule_resource_resource` (`resource_id`, `deleted`),
  KEY `idx_scene_schedule_resource_event` (`event_id`),
  KEY `idx_scene_schedule_resource_booking` (`booking_status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场资源布置表';

CREATE TABLE IF NOT EXISTS `competition_scene_resource_slot` (
  `slot_id` bigint NOT NULL AUTO_INCREMENT COMMENT '预约时段ID',
  `schedule_resource_id` bigint NOT NULL COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `start_time` datetime NOT NULL COMMENT '时段开始时间',
  `end_time` datetime NOT NULL COMMENT '时段结束时间',
  `device_capacity` int NOT NULL COMMENT '本时段可预约设备数',
  `reserved_device_count` int NOT NULL DEFAULT 0 COMMENT '已预约设备数',
  `remaining_device_count` int NOT NULL COMMENT '剩余设备数',
  `workstation_capacity` int NOT NULL COMMENT '本时段工位容量',
  `reserved_workstation_count` int NOT NULL DEFAULT 0 COMMENT '已预约覆盖工位数',
  `remaining_workstation_count` int NOT NULL COMMENT '剩余工位数',
  `slot_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '时段状态: PENDING/OPEN/FULL/CLOSED/EXPIRED',
  `version` bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`slot_id`),
  KEY `idx_scene_resource_slot_schedule_resource` (`schedule_resource_id`, `slot_status`, `deleted`),
  KEY `idx_scene_resource_slot_schedule` (`schedule_id`, `start_time`),
  KEY `idx_scene_resource_slot_resource` (`resource_id`, `start_time`),
  KEY `idx_scene_resource_slot_event` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源预约时段表';

CREATE TABLE IF NOT EXISTS `competition_scene_resource_reservation` (
  `reservation_id` bigint NOT NULL AUTO_INCREMENT COMMENT '资源预约ID',
  `slot_id` bigint NOT NULL COMMENT '预约时段ID',
  `schedule_resource_id` bigint NOT NULL COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `subject_type` varchar(32) NOT NULL COMMENT '预约主体类型: TEAM/USER',
  `subject_code` varchar(128) NOT NULL COMMENT '预约主体编码，团队存team_code，个人存user_id或稳定target引用',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号冗余',
  `user_id` bigint DEFAULT NULL COMMENT '个人预约用户ID或团队预约操作人冗余',
  `operator_user_id` bigint NOT NULL COMMENT '实际操作人用户ID',
  `reserved_device_count` int NOT NULL COMMENT '预约设备数',
  `covered_workstation_count` int NOT NULL COMMENT '覆盖工位数',
  `reservation_status` varchar(32) NOT NULL DEFAULT 'RESERVED' COMMENT '预约状态: RESERVED/CANCELLED/CHECKED',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `check_status` varchar(32) NOT NULL DEFAULT 'UNCHECKED' COMMENT '核销状态: UNCHECKED/CHECKED',
  `check_user_id` bigint DEFAULT NULL COMMENT '核销操作人',
  `check_time` datetime DEFAULT NULL COMMENT '核销时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`reservation_id`),
  UNIQUE KEY `uk_scene_reservation_idempotency` (`idempotency_key`),
  KEY `idx_scene_reservation_slot` (`slot_id`, `reservation_status`, `deleted`),
  KEY `idx_scene_reservation_subject` (`schedule_id`, `subject_type`, `subject_code`, `reservation_status`, `deleted`),
  KEY `idx_scene_reservation_operator` (`operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源预约记录表';
