-- ============================================================
-- 大赛证 / 现场证件 / 资源预约模块数据库迁移合并文件
-- Generated by ChatGPT from uploaded migration scripts
-- Merge date: 2026-07-05
-- Target: MySQL 5.7+/8.0+, utf8mb4
--
-- 建议用途：新测试库/未执行过本模块迁移的数据库初始化。
-- 注意：其中部分 ALTER TABLE ADD COLUMN / ADD KEY 不具备重复执行幂等性；
--       如果目标库已经执行过单个迁移文件，再执行本合并文件可能出现 Duplicate column/key。
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- ============================================================
-- 01 大赛证/现场证件基础表
-- Source: 20260629_competition_scene_credential.sql
-- ============================================================

-- Competition on-site credential and verification tables.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only creates new tables and does not modify existing data.


-- 赛场安排主表：维护报道、赛场、候场、资料领取等真实现场安排。
CREATE TABLE IF NOT EXISTS `competition_scene_schedule` (
  `schedule_id` bigint NOT NULL AUTO_INCREMENT COMMENT '赛场安排ID',
  `schedule_name` varchar(255) NOT NULL COMMENT '安排名称',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `competition_name` varchar(255) DEFAULT NULL COMMENT '赛事名称快照',
  `competition_stage_id` varchar(64) DEFAULT NULL COMMENT '赛事阶段ID',
  `competition_stage_name` varchar(255) DEFAULT NULL COMMENT '赛事阶段名称快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR参赛证/TEACHER教师证/EXPERT专家证',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM团队/PERSON个人',
  `report_start_time` datetime DEFAULT NULL COMMENT '报道开始时间',
  `report_end_time` datetime DEFAULT NULL COMMENT '报道结束时间',
  `report_location` varchar(500) DEFAULT NULL COMMENT '报道地点',
  `contest_start_time` datetime DEFAULT NULL COMMENT '赛场开始时间',
  `contest_end_time` datetime DEFAULT NULL COMMENT '赛场结束时间',
  `contest_location` varchar(500) DEFAULT NULL COMMENT '赛场地点',
  `contest_room` varchar(255) DEFAULT NULL COMMENT '赛场/考场',
  `waiting_start_time` datetime DEFAULT NULL COMMENT '候场开始时间',
  `waiting_end_time` datetime DEFAULT NULL COMMENT '候场结束时间',
  `waiting_location` varchar(500) DEFAULT NULL COMMENT '候场地点',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `material_location` varchar(500) DEFAULT NULL COMMENT '资料领取地点',
  `notice` text COMMENT '注意事项',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态: 0启用/1停用',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`schedule_id`),
  KEY `idx_scene_schedule_series` (`competition_series_id`),
  KEY `idx_scene_schedule_track_group` (`competition_track_id`, `second_level_code`),
  KEY `idx_scene_schedule_type_dimension` (`credential_type`, `config_dimension`),
  KEY `idx_scene_schedule_status` (`status`, `del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场安排表';

-- 赛场安排对象表：记录某个安排匹配到的团队、个人或专家。
CREATE TABLE IF NOT EXISTS `competition_scene_schedule_target` (
  `target_id` bigint NOT NULL AUTO_INCREMENT COMMENT '安排对象ID',
  `schedule_id` bigint NOT NULL COMMENT '赛场安排ID',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR/TEACHER/EXPERT',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM/PERSON',
  `target_key` varchar(128) NOT NULL COMMENT '对象唯一键: TEAM:{teamCode}/PERSON:{memberId}/EXPERT:{manualKey}',
  `target_source` varchar(32) NOT NULL DEFAULT 'APPLY' COMMENT '对象来源: APPLY报名/IMPORT导入/MANUAL手工',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `id_card_type` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `id_card_hash` varchar(128) DEFAULT NULL COMMENT '证件号Hash',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位',
  `school` varchar(64) DEFAULT NULL COMMENT '学校编码',
  `school_name` varchar(255) DEFAULT NULL COMMENT '学校名称',
  `org_id` bigint DEFAULT NULL COMMENT '机构ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '机构名称',
  `competition_role_name` varchar(64) DEFAULT NULL COMMENT '参赛角色',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `leader_teacher_id` bigint DEFAULT NULL COMMENT '带队老师ID',
  `leader_teacher` varchar(100) DEFAULT NULL COMMENT '带队老师',
  `guide_teacher` varchar(500) DEFAULT NULL COMMENT '指导教师',
  `seat_no` varchar(64) DEFAULT NULL COMMENT '座位号/工位号',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `target_snapshot_json` longtext COMMENT '对象报名快照JSON',
  `match_status` varchar(32) NOT NULL DEFAULT 'MATCHED' COMMENT '匹配状态: MATCHED已匹配/CONFLICT冲突/INVALID无效',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态: 0有效/1停用',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`target_id`),
  UNIQUE KEY `uk_scene_target_key` (`schedule_id`, `target_key`),
  KEY `idx_scene_target_schedule` (`schedule_id`, `status`, `del_flag`),
  KEY `idx_scene_target_series` (`competition_series_id`),
  KEY `idx_scene_target_team` (`team_code`),
  KEY `idx_scene_target_member` (`member_id`),
  KEY `idx_scene_target_user` (`user_id`),
  KEY `idx_scene_target_track_group` (`competition_track_id`, `second_level_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场安排对象表';

-- 现场证件实例表：每个团队、个人或专家生成一张可扫码核验的证件。
CREATE TABLE IF NOT EXISTS `competition_scene_credential` (
  `credential_id` bigint NOT NULL AUTO_INCREMENT COMMENT '现场证件ID',
  `schedule_id` bigint NOT NULL COMMENT '赛场安排ID',
  `target_id` bigint DEFAULT NULL COMMENT '安排对象ID',
  `credential_no` varchar(64) NOT NULL COMMENT '证件编号',
  `credential_token` varchar(128) NOT NULL COMMENT '二维码令牌',
  `qr_content` varchar(1000) DEFAULT NULL COMMENT '二维码内容',
  `qr_code_url` varchar(1000) DEFAULT NULL COMMENT '二维码图片URL',
  `credential_file_url` varchar(1000) DEFAULT NULL COMMENT '参赛证文件URL',
  `credential_image_url` varchar(1000) DEFAULT NULL COMMENT '参赛证图片URL',
  `credential_type` varchar(32) NOT NULL COMMENT '证件类型: COMPETITOR参赛证/TEACHER教师证/EXPERT专家证',
  `config_dimension` varchar(32) NOT NULL COMMENT '配置维度: TEAM/PERSON',
  `subject_type` varchar(32) NOT NULL COMMENT '证件主体: TEAM团队/PERSON个人/EXPERT专家',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `competition_name` varchar(255) DEFAULT NULL COMMENT '赛事名称快照',
  `competition_stage_id` varchar(64) DEFAULT NULL COMMENT '赛事阶段ID',
  `competition_stage_name` varchar(255) DEFAULT NULL COMMENT '赛事阶段名称快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `id_card_type` varchar(32) DEFAULT NULL COMMENT '证件类型',
  `id_card_hash` varchar(128) DEFAULT NULL COMMENT '证件号Hash',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位',
  `school` varchar(64) DEFAULT NULL COMMENT '学校编码',
  `school_name` varchar(255) DEFAULT NULL COMMENT '学校名称',
  `org_id` bigint DEFAULT NULL COMMENT '机构ID',
  `org_name` varchar(255) DEFAULT NULL COMMENT '机构名称',
  `competition_role_name` varchar(64) DEFAULT NULL COMMENT '参赛角色',
  `leader_teacher_id` bigint DEFAULT NULL COMMENT '带队老师ID',
  `leader_teacher` varchar(100) DEFAULT NULL COMMENT '带队老师',
  `guide_teacher` varchar(500) DEFAULT NULL COMMENT '指导教师',
  `report_start_time` datetime DEFAULT NULL COMMENT '报道开始时间快照',
  `report_end_time` datetime DEFAULT NULL COMMENT '报道结束时间快照',
  `report_location` varchar(500) DEFAULT NULL COMMENT '报道地点快照',
  `contest_start_time` datetime DEFAULT NULL COMMENT '赛场开始时间快照',
  `contest_end_time` datetime DEFAULT NULL COMMENT '赛场结束时间快照',
  `contest_location` varchar(500) DEFAULT NULL COMMENT '赛场地点快照',
  `contest_room` varchar(255) DEFAULT NULL COMMENT '赛场/考场快照',
  `seat_no` varchar(64) DEFAULT NULL COMMENT '座位号/工位号',
  `waiting_start_time` datetime DEFAULT NULL COMMENT '候场开始时间快照',
  `waiting_end_time` datetime DEFAULT NULL COMMENT '候场结束时间快照',
  `waiting_location` varchar(500) DEFAULT NULL COMMENT '候场地点快照',
  `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码',
  `waiting_group_name` varchar(255) DEFAULT NULL COMMENT '候场分组名称',
  `material_location` varchar(500) DEFAULT NULL COMMENT '资料领取地点快照',
  `notice` text COMMENT '注意事项快照',
  `credential_snapshot_json` longtext COMMENT '证件生成快照JSON',
  `valid_from` datetime DEFAULT NULL COMMENT '有效开始时间',
  `valid_to` datetime DEFAULT NULL COMMENT '有效结束时间',
  `credential_status` varchar(32) NOT NULL DEFAULT 'EFFECTIVE' COMMENT '证件状态: EFFECTIVE有效/REVOKED作废/EXPIRED过期',
  `verify_count` int NOT NULL DEFAULT 0 COMMENT '核验次数',
  `last_verify_time` datetime DEFAULT NULL COMMENT '最后核验时间',
  `report_status` char(1) NOT NULL DEFAULT '0' COMMENT '报道状态: 0未报到/1已报到',
  `report_time` datetime DEFAULT NULL COMMENT '报道时间',
  `report_operator_id` bigint DEFAULT NULL COMMENT '报道操作人ID',
  `report_operator_name` varchar(100) DEFAULT NULL COMMENT '报道操作人',
  `material_status` char(1) NOT NULL DEFAULT '0' COMMENT '资料领取状态: 0未领取/1已领取',
  `material_time` datetime DEFAULT NULL COMMENT '资料领取时间',
  `material_receiver_name` varchar(100) DEFAULT NULL COMMENT '资料领取人',
  `material_receiver_phone` varchar(32) DEFAULT NULL COMMENT '资料领取人手机号',
  `material_receiver_id_suffix` varchar(16) DEFAULT NULL COMMENT '资料领取人证件后六位',
  `material_operator_id` bigint DEFAULT NULL COMMENT '资料领取操作人ID',
  `material_operator_name` varchar(100) DEFAULT NULL COMMENT '资料领取操作人',
  `waiting_status` char(1) NOT NULL DEFAULT '0' COMMENT '候场状态: 0未候场/1已候场',
  `waiting_time` datetime DEFAULT NULL COMMENT '候场确认时间',
  `waiting_operator_id` bigint DEFAULT NULL COMMENT '候场操作人ID',
  `waiting_operator_name` varchar(100) DEFAULT NULL COMMENT '候场操作人',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`credential_id`),
  UNIQUE KEY `uk_scene_credential_no` (`credential_no`),
  UNIQUE KEY `uk_scene_credential_token` (`credential_token`),
  KEY `idx_scene_credential_schedule` (`schedule_id`),
  KEY `idx_scene_credential_target` (`target_id`),
  KEY `idx_scene_credential_series` (`competition_series_id`),
  KEY `idx_scene_credential_team` (`team_code`),
  KEY `idx_scene_credential_member` (`member_id`),
  KEY `idx_scene_credential_user` (`user_id`),
  KEY `idx_scene_credential_track_group` (`competition_track_id`, `second_level_code`),
  KEY `idx_scene_credential_status` (`credential_status`, `del_flag`),
  KEY `idx_scene_credential_report` (`report_status`, `report_time`),
  KEY `idx_scene_credential_material` (`material_status`, `material_time`),
  KEY `idx_scene_credential_waiting` (`waiting_status`, `waiting_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场证件实例表';

-- 现场操作流水表：记录扫码核验、报到签到、资料领取、候场确认及失败/重复操作。
CREATE TABLE IF NOT EXISTS `competition_scene_operation_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '现场操作日志ID',
  `credential_id` bigint DEFAULT NULL COMMENT '现场证件ID',
  `schedule_id` bigint DEFAULT NULL COMMENT '赛场安排ID',
  `target_id` bigint DEFAULT NULL COMMENT '安排对象ID',
  `competition_series_id` bigint DEFAULT NULL COMMENT '赛事系列ID',
  `credential_no` varchar(64) DEFAULT NULL COMMENT '证件编号',
  `credential_token` varchar(128) DEFAULT NULL COMMENT '二维码令牌',
  `operation_type` varchar(32) NOT NULL COMMENT '操作类型: VERIFY核验/REPORT_SIGN报道/MATERIAL_RECEIVE资料领取/WAITING_CHECK_IN候场',
  `operation_stage` varchar(32) NOT NULL DEFAULT 'CONFIRM' COMMENT '操作阶段: SCAN扫码/CONFIRM确认',
  `operation_result` varchar(32) NOT NULL COMMENT '操作结果: PASS通过/FAIL失败/DUPLICATE重复/EXCEPTION异常',
  `result_message` varchar(500) DEFAULT NULL COMMENT '结果说明',
  `apply_check_result` varchar(32) DEFAULT NULL COMMENT '报名一致性校验结果',
  `schedule_check_result` varchar(32) DEFAULT NULL COMMENT '赛场安排校验结果',
  `identity_check_result` varchar(32) DEFAULT NULL COMMENT '身份校验结果',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号快照',
  `team_name` varchar(255) DEFAULT NULL COMMENT '团队名称快照',
  `member_id` bigint DEFAULT NULL COMMENT '报名成员ID快照',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID快照',
  `user_name` varchar(100) DEFAULT NULL COMMENT '姓名快照',
  `id_card_suffix` varchar(16) DEFAULT NULL COMMENT '证件号后六位快照',
  `competition_track_id` varchar(64) DEFAULT NULL COMMENT '赛道ID快照',
  `competition_track_name` varchar(255) DEFAULT NULL COMMENT '赛道名称快照',
  `second_level_code` varchar(64) DEFAULT NULL COMMENT '组别编码快照',
  `second_level_name` varchar(255) DEFAULT NULL COMMENT '组别名称快照',
  `receiver_name` varchar(100) DEFAULT NULL COMMENT '资料领取人',
  `receiver_phone` varchar(32) DEFAULT NULL COMMENT '资料领取人手机号',
  `receiver_id_suffix` varchar(16) DEFAULT NULL COMMENT '资料领取人证件后六位',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人姓名',
  `operator_phone` varchar(32) DEFAULT NULL COMMENT '操作人手机号',
  `operator_open_id` varchar(128) DEFAULT NULL COMMENT '操作人微信OpenID',
  `scan_ip` varchar(128) DEFAULT NULL COMMENT '扫码IP',
  `device_info` varchar(500) DEFAULT NULL COMMENT '设备信息',
  `operation_time` datetime NOT NULL COMMENT '操作时间',
  `request_payload` longtext COMMENT '请求参数JSON',
  `response_payload` longtext COMMENT '响应结果JSON',
  `apply_snapshot_json` longtext COMMENT '当前报名快照JSON',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `version` bigint DEFAULT 0 COMMENT '版本',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`log_id`),
  KEY `idx_scene_log_credential` (`credential_id`),
  KEY `idx_scene_log_schedule` (`schedule_id`),
  KEY `idx_scene_log_series` (`competition_series_id`),
  KEY `idx_scene_log_operation` (`operation_type`, `operation_stage`, `operation_result`),
  KEY `idx_scene_log_time` (`operation_time`),
  KEY `idx_scene_log_team` (`team_code`),
  KEY `idx_scene_log_member` (`member_id`),
  KEY `idx_scene_log_user` (`user_id`),
  KEY `idx_scene_log_operator` (`operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场扫码操作流水表';


-- ============================================================
-- 02 资源预约基础表
-- Source: 20260701_competition_scene_resource_p1_001.sql
-- ============================================================

-- Competition scene resource phase 1 tables.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only creates new tables and does not modify existing data.


CREATE TABLE IF NOT EXISTS `competition_scene_resource` (
  `resource_id` bigint NOT NULL AUTO_INCREMENT COMMENT '资源ID',
  `resource_code` varchar(64) NOT NULL COMMENT '资源编号',
  `resource_name` varchar(255) NOT NULL COMMENT '资源名称',
  `resource_type` varchar(32) NOT NULL COMMENT '资源类型: ROOM/LAB/DEVICE/WORKSTATION/SERVER/SOFTWARE/OTHER',
  `resource_status` varchar(32) NOT NULL COMMENT '资源状态: ENABLED启用/DISABLED停用/MAINTENANCE维护中',
  `brand_model` varchar(255) DEFAULT NULL COMMENT '品牌型号',
  `device_quantity` int NOT NULL COMMENT '设备数量',
  `workstation_count` int NOT NULL COMMENT '单台设备工位数',
  `default_slot_duration_minutes` int NOT NULL COMMENT '默认单场占用周期，单位分钟',
  `default_shared_occupancy` tinyint(1) NOT NULL DEFAULT 1 COMMENT '默认是否共享占用: 0否/1是',
  `need_ops_confirm` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要运维确认，仅提示字段: 0否/1是',
  `ops_contact_name` varchar(100) DEFAULT NULL COMMENT '运维联系人',
  `ops_contact_phone` varchar(32) DEFAULT NULL COMMENT '运维联系电话',
  `safety_notice` text COMMENT '安全须知',
  `attention_notes` text COMMENT '注意事项',
  `parameter_json` longtext COMMENT '主要参数列表JSON',
  `usage_instructions` text COMMENT '使用说明',
  `image_urls` longtext COMMENT '设备图片URL JSON数组',
  `admin_remark` varchar(500) DEFAULT NULL COMMENT '管理员备注',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`resource_id`),
  UNIQUE KEY `uk_scene_resource_code` (`resource_code`, `deleted`),
  KEY `idx_scene_resource_type` (`resource_type`),
  KEY `idx_scene_resource_status` (`resource_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源台账表';

CREATE TABLE IF NOT EXISTS `competition_scene_schedule_resource` (
  `schedule_resource_id` bigint NOT NULL AUTO_INCREMENT COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `deployment_location` varchar(500) DEFAULT NULL COMMENT '部署位置',
  `deployed_device_count` int NOT NULL COMMENT '部署设备数',
  `workstations_per_device` int NOT NULL COMMENT '每台设备工位数',
  `total_workstations` int NOT NULL COMMENT '总工位数',
  `slot_duration_minutes` int NOT NULL COMMENT '单场占用周期，单位分钟',
  `shared_occupancy` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否共享占用: 0否/1是',
  `need_ops_confirm` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否需要运维确认，仅提示字段: 0否/1是',
  `ops_contact_name` varchar(100) DEFAULT NULL COMMENT '运维联系人',
  `ops_contact_phone` varchar(32) DEFAULT NULL COMMENT '运维联系电话',
  `booking_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '预约发布状态: DRAFT/READY/OPEN/PAUSED/CLOSED',
  `booking_open_time` datetime DEFAULT NULL COMMENT '预约开放时间',
  `booking_close_time` datetime DEFAULT NULL COMMENT '预约关闭时间',
  `safety_notice_override` text COMMENT '安全须知覆盖',
  `attention_notes_override` text COMMENT '注意事项覆盖',
  `usage_instructions_override` text COMMENT '使用说明覆盖',
  `admin_remark` varchar(500) DEFAULT NULL COMMENT '管理员备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`schedule_resource_id`),
  KEY `idx_scene_schedule_resource_schedule` (`schedule_id`, `deleted`),
  KEY `idx_scene_schedule_resource_resource` (`resource_id`, `deleted`),
  KEY `idx_scene_schedule_resource_event` (`event_id`),
  KEY `idx_scene_schedule_resource_booking` (`booking_status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场赛场资源布置表';

CREATE TABLE IF NOT EXISTS `competition_scene_resource_slot` (
  `slot_id` bigint NOT NULL AUTO_INCREMENT COMMENT '预约时段ID',
  `schedule_resource_id` bigint NOT NULL COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `start_time` datetime NOT NULL COMMENT '时段开始时间',
  `end_time` datetime NOT NULL COMMENT '时段结束时间',
  `device_capacity` int NOT NULL COMMENT '本时段可预约设备数',
  `reserved_device_count` int NOT NULL DEFAULT 0 COMMENT '已预约设备数',
  `remaining_device_count` int NOT NULL COMMENT '剩余设备数',
  `workstation_capacity` int NOT NULL COMMENT '本时段工位容量',
  `reserved_workstation_count` int NOT NULL DEFAULT 0 COMMENT '已预约覆盖工位数',
  `remaining_workstation_count` int NOT NULL COMMENT '剩余工位数',
  `slot_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '时段状态: PENDING/OPEN/FULL/CLOSED/EXPIRED',
  `version` bigint NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`slot_id`),
  KEY `idx_scene_resource_slot_schedule_resource` (`schedule_resource_id`, `slot_status`, `deleted`),
  KEY `idx_scene_resource_slot_schedule` (`schedule_id`, `start_time`),
  KEY `idx_scene_resource_slot_resource` (`resource_id`, `start_time`),
  KEY `idx_scene_resource_slot_event` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源预约时段表';

CREATE TABLE IF NOT EXISTS `competition_scene_resource_reservation` (
  `reservation_id` bigint NOT NULL AUTO_INCREMENT COMMENT '资源预约ID',
  `slot_id` bigint NOT NULL COMMENT '预约时段ID',
  `schedule_resource_id` bigint NOT NULL COMMENT '赛场资源布置ID',
  `schedule_id` bigint NOT NULL COMMENT '现场安排ID',
  `resource_id` bigint NOT NULL COMMENT '资源ID',
  `event_id` bigint DEFAULT NULL COMMENT '现场活动ID，第一阶段使用赛事系列ID',
  `subject_type` varchar(32) NOT NULL COMMENT '预约主体类型: TEAM/USER',
  `subject_code` varchar(128) NOT NULL COMMENT '预约主体编码，团队存team_code，个人存user_id或稳定target引用',
  `team_code` varchar(64) DEFAULT NULL COMMENT '团队编号冗余',
  `user_id` bigint DEFAULT NULL COMMENT '个人预约用户ID或团队预约操作人冗余',
  `operator_user_id` bigint NOT NULL COMMENT '实际操作人用户ID',
  `reserved_device_count` int NOT NULL COMMENT '预约设备数',
  `covered_workstation_count` int NOT NULL COMMENT '覆盖工位数',
  `reservation_status` varchar(32) NOT NULL DEFAULT 'RESERVED' COMMENT '预约状态: RESERVED/CANCELLED/CHECKED',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `check_status` varchar(32) NOT NULL DEFAULT 'UNCHECKED' COMMENT '核销状态: UNCHECKED/CHECKED',
  `check_user_id` bigint DEFAULT NULL COMMENT '核销操作人',
  `check_time` datetime DEFAULT NULL COMMENT '核销时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`reservation_id`),
  UNIQUE KEY `uk_scene_reservation_idempotency` (`idempotency_key`),
  KEY `idx_scene_reservation_slot` (`slot_id`, `reservation_status`, `deleted`),
  KEY `idx_scene_reservation_subject` (`schedule_id`, `subject_type`, `subject_code`, `reservation_status`, `deleted`),
  KEY `idx_scene_reservation_operator` (`operator_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场设备资源预约记录表';


-- ============================================================
-- 03 证件类型与角色口径调整
-- Source: 20260701_competition_scene_target_credential_type.sql
-- ============================================================

-- Competition scene target credential type口径调整。
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- 本脚本仅供人工审查后执行，不连接生产库，不删除旧字段。


-- 字段已在 20260629_competition_scene_credential.sql 中创建，本轮仅更新注释口径。
ALTER TABLE `competition_scene_schedule`
  MODIFY COLUMN `credential_type` varchar(32) NOT NULL COMMENT '历史兼容字段：证件类型已迁移到competition_scene_schedule_target.credential_type',
  MODIFY COLUMN `config_dimension` varchar(32) NOT NULL COMMENT '历史兼容字段：新安排默认按PERSON对象匹配',
  MODIFY COLUMN `waiting_group_code` varchar(64) DEFAULT NULL COMMENT '候场分组编码：系统维护，不再由前端手工录入';

ALTER TABLE `competition_scene_schedule_target`
  MODIFY COLUMN `credential_type` varchar(32) NOT NULL COMMENT '证件类型：PARTICIPANT参赛证/TEACHER教师证/EXPERT专家证/STAFF工作人员证',
  MODIFY COLUMN `competition_role_name` varchar(64) DEFAULT NULL COMMENT '现场角色：TEACHER/MEMBER/EXPERT/CAPTAIN/MATERIAL_STAFF/CHECKIN_STAFF';

ALTER TABLE `competition_scene_credential`
  MODIFY COLUMN `credential_type` varchar(32) NOT NULL COMMENT '证件类型：PARTICIPANT参赛证/TEACHER教师证/EXPERT专家证/STAFF工作人员证',
  MODIFY COLUMN `competition_role_name` varchar(64) DEFAULT NULL COMMENT '现场角色快照：TEACHER/MEMBER/EXPERT/CAPTAIN/MATERIAL_STAFF/CHECKIN_STAFF';

-- 说明：
-- 1. competition_scene_schedule_target.credential_type 已存在，无需重复 ADD COLUMN。
-- 2. competition_scene_credential.uk_scene_credential_no 已存在，无需重复 ADD UNIQUE KEY。
-- 3. 旧值 COMPETITOR 由代码兼容并在后续写入时归一为 PARTICIPANT。
-- 4. 如确认不再需要旧值，可人工审查后执行：
-- UPDATE competition_scene_schedule_target SET credential_type = 'PARTICIPANT' WHERE credential_type = 'COMPETITOR';
-- UPDATE competition_scene_credential SET credential_type = 'PARTICIPANT' WHERE credential_type = 'COMPETITOR';


-- ============================================================
-- 04 证件作用域与主体操作状态升级
-- Source: 20260702_competition_scene_credential_scope_p1.sql
-- ============================================================

-- Competition scene credential scope and subject operation state upgrade.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- Do not run against production before review.


ALTER TABLE `competition_scene_credential`
  MODIFY COLUMN `schedule_id` bigint DEFAULT NULL COMMENT '赛场安排ID，赛场级证件必填，大赛级直接发证可为空',
  ADD COLUMN `issue_channel` varchar(32) NOT NULL DEFAULT 'SCHEDULE_MATCH' COMMENT '发证渠道: SCHEDULE_MATCH赛场匹配/COMPETITION_DIRECT大赛直接/MANUAL手工/IMPORT导入' AFTER `credential_image_url`,
  ADD COLUMN `scope_type` varchar(32) NOT NULL DEFAULT 'SCHEDULE' COMMENT '证件作用域: COMPETITION大赛/SCHEDULE赛场/VIP贵宾/EXPERT专家/STAFF工作人员/TEMP临时' AFTER `issue_channel`,
  ADD COLUMN `scope_ref_id` bigint DEFAULT NULL COMMENT '作用域引用ID: 大赛级为competition_series_id，赛场级为schedule_id' AFTER `scope_type`,
  ADD COLUMN `credential_name` varchar(100) DEFAULT NULL COMMENT '证件展示名称，与credential_type解耦' AFTER `scope_ref_id`,
  ADD COLUMN `ability_json` text COMMENT '证件能力JSON，固定字段report/material/waiting/review/resourceReservation/vipAccess' AFTER `credential_name`;

ALTER TABLE `competition_scene_credential`
  ADD KEY `idx_scene_credential_scope` (`scope_type`, `scope_ref_id`),
  ADD KEY `idx_scene_credential_issue` (`issue_channel`),
  ADD KEY `idx_scene_credential_name` (`credential_name`);

UPDATE `competition_scene_credential`
SET `issue_channel` = 'SCHEDULE_MATCH',
    `scope_type` = 'SCHEDULE',
    `scope_ref_id` = `schedule_id`,
    `credential_name` = CASE
      WHEN `credential_type` IN ('PARTICIPANT', 'COMPETITOR') THEN '参赛证'
      WHEN `credential_type` = 'TEACHER' THEN '教师证'
      WHEN `credential_type` = 'EXPERT' THEN '专家证'
      WHEN `credential_type` = 'STAFF' THEN '工作证'
      ELSE '现场证件'
    END,
    `ability_json` = CASE
      WHEN `credential_type` IN ('PARTICIPANT', 'COMPETITOR') THEN '{"report":true,"material":true,"waiting":true,"review":false,"resourceReservation":true,"vipAccess":false}'
      WHEN `credential_type` = 'TEACHER' THEN '{"report":true,"material":false,"waiting":false,"review":false,"resourceReservation":false,"vipAccess":false}'
      WHEN `credential_type` = 'EXPERT' THEN '{"report":true,"material":false,"waiting":false,"review":true,"resourceReservation":false,"vipAccess":false}'
      WHEN `credential_type` = 'STAFF' THEN '{"report":false,"material":false,"waiting":false,"review":false,"resourceReservation":false,"vipAccess":false}'
      ELSE '{"report":false,"material":false,"waiting":false,"review":false,"resourceReservation":false,"vipAccess":false}'
    END
WHERE `scope_ref_id` IS NULL
  AND `del_flag` = '0';

CREATE TABLE IF NOT EXISTS `competition_scene_subject_operation_state` (
  `state_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主体操作状态ID',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `scope_type` varchar(32) NOT NULL COMMENT '状态作用域: COMPETITION/SCHEDULE/VIP/EXPERT/STAFF/TEMP',
  `scope_ref_id` bigint NOT NULL COMMENT '状态作用域引用ID',
  `subject_type` varchar(32) NOT NULL COMMENT '主体类型: TEAM/USER/EXPERT/STAFF/VIP/TEMP',
  `subject_code` varchar(128) NOT NULL COMMENT '主体编码: team_code/user_id/稳定外部编码',
  `operation_type` varchar(32) NOT NULL COMMENT '操作类型: REPORT/MATERIAL/WAITING',
  `operation_status` varchar(32) NOT NULL COMMENT '操作状态: DONE/CANCELLED/INVALID',
  `operation_time` datetime DEFAULT NULL COMMENT '操作完成时间',
  `credential_id` bigint DEFAULT NULL COMMENT '触发操作的证件ID',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人姓名',
  `delegate_user_id` bigint DEFAULT NULL COMMENT '代领人用户ID',
  `delegate_name` varchar(100) DEFAULT NULL COMMENT '代领人姓名',
  `delegate_credential_id` bigint DEFAULT NULL COMMENT '代领人证件ID',
  `delegate_relation` varchar(64) DEFAULT NULL COMMENT '代领关系: SELF本人/TEAM_MEMBER同队成员',
  `last_log_id` bigint DEFAULT NULL COMMENT '最近一次成功操作流水ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`state_id`),
  KEY `idx_scene_subject_operation_lookup` (`competition_series_id`, `scope_type`, `scope_ref_id`, `subject_type`, `subject_code`, `operation_type`, `operation_status`, `deleted`),
  KEY `idx_scene_subject_operation_series` (`competition_series_id`),
  KEY `idx_scene_subject_operation_scope` (`scope_type`, `scope_ref_id`),
  KEY `idx_scene_subject_operation_subject` (`subject_type`, `subject_code`),
  KEY `idx_scene_subject_operation_credential` (`credential_id`),
  KEY `idx_scene_subject_operation_delegate` (`delegate_user_id`),
  KEY `idx_scene_subject_operation_log` (`last_log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场主体操作状态表';


-- ============================================================
-- 05 大赛级直接发证支持
-- Source: 20260702_competition_scene_credential_direct_issue_p2.sql
-- ============================================================

-- Competition-level direct scene credential issue support.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- Do not run against production before review.


ALTER TABLE `competition_scene_credential`
  ADD COLUMN `subject_code` varchar(128) DEFAULT NULL COMMENT '证件主体编码: team_code/user_id/稳定外部编码' AFTER `subject_type`;

ALTER TABLE `competition_scene_credential`
  ADD KEY `idx_scene_credential_subject_code` (`subject_type`, `subject_code`),
  ADD KEY `idx_scene_credential_competition_subject` (`competition_series_id`, `scope_type`, `subject_type`, `subject_code`, `credential_type`, `credential_status`, `del_flag`);

UPDATE `competition_scene_credential`
SET `subject_code` = CASE
  WHEN `subject_type` = 'TEAM' THEN `team_code`
  WHEN `user_id` IS NOT NULL THEN CAST(`user_id` AS CHAR)
  WHEN `member_id` IS NOT NULL THEN CONCAT('MEMBER:', `member_id`)
  ELSE NULL
END
WHERE `subject_code` IS NULL
  AND `del_flag` = '0';


-- ============================================================
-- 06 一卡通有效核心证件唯一键
-- Source: 20260705_competition_scene_credential_active_core_key_p2.sql
-- ============================================================

-- Competition scene credential one-card active core credential key.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only adds a nullable key column and unique index. It does not migrate or clean legacy test data.


ALTER TABLE `competition_scene_credential`
  ADD COLUMN `active_core_credential_key` varchar(255) DEFAULT NULL
    COMMENT '有效核心证件唯一键，COMPETITION且EFFECTIVE且del_flag=0时写入competitionSeriesId:subjectType:subjectCode:credentialType，撤销/删除/失效后置空'
    AFTER `scope_ref_id`;

ALTER TABLE `competition_scene_credential`
  ADD UNIQUE KEY `uk_scene_credential_active_core_key` (`active_core_credential_key`);


-- ============================================================
-- 07 证件作用域授权试点表
-- Source: 20260705_competition_scene_credential_scope_grant_pilot_p1.sql
-- ============================================================

-- Competition scene credential one-card grant pilot phase 1.
-- Target database: MySQL 5.7+/8.0+, charset utf8mb4.
-- This migration only creates the grant table. It does not migrate legacy test data.


CREATE TABLE IF NOT EXISTS `competition_scene_credential_scope_grant` (
  `grant_id` bigint NOT NULL AUTO_INCREMENT COMMENT '证件授权ID',
  `credential_id` bigint NOT NULL COMMENT '核心现场证件ID',
  `competition_series_id` bigint NOT NULL COMMENT '赛事系列ID',
  `scope_type` varchar(32) NOT NULL COMMENT '授权作用域: COMPETITION/SCHEDULE/VIP/EXPERT/STAFF/TEMP',
  `scope_ref_id` bigint NOT NULL COMMENT '授权作用域引用ID，当前约定所有scope_ref_id均为内部数值ID，SCHEDULE为schedule_id',
  `active_grant_key` varchar(255) DEFAULT NULL COMMENT '有效授权唯一键，ACTIVE且deleted=0时写入credentialId:scopeType:scopeRefId:sourceTargetId，撤销后置空',
  `source_type` varchar(32) NOT NULL DEFAULT 'MANUAL' COMMENT '授权来源类型: SCHEDULE_TARGET/MANUAL/IMPORT/COMPETITION_DIRECT',
  `source_schedule_id` bigint DEFAULT NULL COMMENT '来源赛场安排ID',
  `source_target_id` bigint DEFAULT NULL COMMENT '来源赛场安排对象ID',
  `credential_type` varchar(32) NOT NULL COMMENT '授权对应证件类型',
  `role_code` varchar(64) DEFAULT NULL COMMENT '授权角色编码',
  `subject_type` varchar(32) NOT NULL COMMENT '主体类型',
  `subject_code` varchar(128) NOT NULL COMMENT '主体编码',
  `ability_json` text COMMENT '授权能力JSON',
  `valid_from` datetime DEFAULT NULL COMMENT '授权有效开始时间',
  `valid_to` datetime DEFAULT NULL COMMENT '授权有效结束时间',
  `operation_window_json` longtext COMMENT '动作窗口JSON',
  `grant_status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '授权状态: ACTIVE有效/REVOKED撤销/EXPIRED过期',
  `grant_snapshot_json` longtext COMMENT '授权快照JSON，不记录手机号、身份证号、token等敏感信息',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标识: 0正常/1删除',
  PRIMARY KEY (`grant_id`),
  UNIQUE KEY `uk_grant_active_key` (`active_grant_key`),
  KEY `idx_grant_credential` (`credential_id`, `deleted`),
  KEY `idx_grant_competition_scope` (`competition_series_id`, `scope_type`, `scope_ref_id`, `deleted`),
  KEY `idx_grant_source_schedule_target` (`source_schedule_id`, `source_target_id`, `deleted`),
  KEY `idx_grant_subject` (`competition_series_id`, `subject_type`, `subject_code`, `credential_type`, `deleted`),
  KEY `idx_grant_status` (`grant_status`, `deleted`),
  KEY `idx_grant_active_lookup` (`credential_id`, `scope_type`, `scope_ref_id`, `source_target_id`, `grant_status`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='赛事现场证件作用域授权表';


-- ============================================================
-- 08 现场安排/证件管理菜单
-- Source: 20260629_competition_scene_admin_menu.sql
-- ============================================================

-- Optional admin menu for competition scene schedule configuration.
-- Run after backend/frontend deployment if the menu does not already exist.

SET @parentId := (
  SELECT menu_id
  FROM sys_menu
  WHERE menu_type = 'M'
    AND menu_name IN ('赛事管理', '赛事中心', '竞赛管理', '大赛管理')
  ORDER BY menu_id
  LIMIT 1
);

SET @parentId := IFNULL(@parentId, 0);

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT
  '现场安排配置', @parentId, 80, 'sceneSchedule', 'tournament/sceneSchedule/index',
  1, 0, 'C', '0', '0', 'competition:sceneSchedule:list', 'date', 'admin', SYSDATE(), '', NULL, '赛事现场安排配置菜单'
WHERE NOT EXISTS (
  SELECT 1 FROM sys_menu WHERE component = 'tournament/sceneSchedule/index'
);

SET @sceneScheduleMenuId := (
  SELECT menu_id
  FROM sys_menu
  WHERE component = 'tournament/sceneSchedule/index'
  ORDER BY menu_id DESC
  LIMIT 1
);

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场安排查询', @sceneScheduleMenuId, 1, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneSchedule:query', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneSchedule:query');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场安排新增', @sceneScheduleMenuId, 2, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneSchedule:add', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneSchedule:add');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场安排修改', @sceneScheduleMenuId, 3, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneSchedule:edit', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneSchedule:edit');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场安排删除', @sceneScheduleMenuId, 4, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneSchedule:remove', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneSchedule:remove');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场证件查询', @sceneScheduleMenuId, 5, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneCredential:list', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneCredential:list');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场证件详情', @sceneScheduleMenuId, 6, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneCredential:query', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneCredential:query');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场证件生成', @sceneScheduleMenuId, 7, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneCredential:add', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneCredential:add');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场证件维护', @sceneScheduleMenuId, 8, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneCredential:edit', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneCredential:edit');

INSERT INTO sys_menu
  (menu_name, parent_id, order_num, path, component, is_frame, is_cache, menu_type,
   visible, status, perms, icon, create_by, create_time, update_by, update_time, remark)
SELECT '现场流水查询', @sceneScheduleMenuId, 9, '#', '', 1, 0, 'F', '0', '0',
       'competition:sceneVerify:list', '#', 'admin', SYSDATE(), '', NULL, ''
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = @sceneScheduleMenuId AND perms = 'competition:sceneVerify:list');


-- ============================================================
-- 09 资源管理菜单
-- Source: 20260701_competition_scene_resource_phase2_menu.sql
-- ============================================================

-- Competition scene resource phase 2 admin menu.
-- This script adds the admin menu and button permissions for scene resource management.
-- It does not hard-code parent menu id; parent menu is resolved by menu name/path.


SET @parent_id := (
    SELECT menu_id
    FROM sys_menu
    WHERE menu_name = '赛事管理'
      AND path = 'tournament'
      AND menu_type = 'M'
      AND platform_type = 'admin'
    ORDER BY menu_id
    LIMIT 1
);

INSERT INTO sys_menu (
    menu_name, parent_id, order_num, path, component, query, route_name,
    is_frame, is_cache, menu_type, visible, status, perms, icon,
    create_by, create_time, remark, platform_type
)
SELECT
    '资源管理', @parent_id, 81, 'sceneResource', 'tournament/sceneResource/index', NULL, 'SceneResource',
    1, 0, 'C', '0', '0', 'competition:sceneResource:list', 'tool',
    'phase2', NOW(), '大赛现场设备资源管理', 'admin'
WHERE @parent_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM sys_menu
      WHERE path = 'sceneResource'
        AND component = 'tournament/sceneResource/index'
        AND platform_type = 'admin'
  );

SET @resource_menu_id := (
    SELECT menu_id
    FROM sys_menu
    WHERE path = 'sceneResource'
      AND component = 'tournament/sceneResource/index'
      AND platform_type = 'admin'
    ORDER BY menu_id
    LIMIT 1
);

INSERT INTO sys_menu (
    menu_name, parent_id, order_num, path, component, query, route_name,
    is_frame, is_cache, menu_type, visible, status, perms, icon,
    create_by, create_time, remark, platform_type
)
SELECT
    btn.menu_name, @resource_menu_id, btn.order_num, '#', NULL, NULL, '',
    1, 0, 'F', '0', '0', btn.perms, '#',
    'phase2', NOW(), btn.remark, 'admin'
FROM (
    SELECT '资源查询' AS menu_name, 1 AS order_num, 'competition:sceneResource:list' AS perms, '资源管理列表权限' AS remark
    UNION ALL SELECT '资源详情', 2, 'competition:sceneResource:query', '资源管理详情权限'
    UNION ALL SELECT '资源新增', 3, 'competition:sceneResource:add', '资源管理新增权限'
    UNION ALL SELECT '资源修改', 4, 'competition:sceneResource:edit', '资源管理修改权限'
    UNION ALL SELECT '资源删除', 5, 'competition:sceneResource:remove', '资源管理删除权限'
    UNION ALL SELECT '资源状态变更', 6, 'competition:sceneResource:changeStatus', '资源管理状态变更权限'
) btn
WHERE @resource_menu_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM sys_menu m
      WHERE m.perms = btn.perms
        AND m.platform_type = 'admin'
  );



-- ============================================================
-- 合并迁移结束
-- ============================================================
SET FOREIGN_KEY_CHECKS = 1;
