/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ds_blank_spacing: typeof import('./components/DS_C/ds_blank_spacing.vue')['default']
    Ds_global_banner: typeof import('./components/DS_C/ds_global_banner.vue')['default']
    Ds_hyperlink: typeof import('./components/DS_C/ds_hyperlink.vue')['default']
    Ds_information: typeof import('./components/DS_C/ds_information.vue')['default']
    Ds_information_home: typeof import('./components/DS_C/ds_information_home.vue')['default']
    Ds_learn_home: typeof import('./components/DS_C/ds_learn_home.vue')['default']
    Ds_list_one: typeof import('./components/DS_C/ds_list_one.vue')['default']
    Ds_support_home: typeof import('./components/DS_C/ds_support_home.vue')['default']
    Ds_text: typeof import('./components/DS_C/ds_text.vue')['default']
    Ds_tournament_home: typeof import('./components/DS_C/ds_tournament_home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
